---
abstract: 'Allows a DBIx::Class user to define a Object::Enum column'
author:
  - 'Jason M. Mills <jmmills@cpan.org>'
build_requires:
  DBICx::TestDatabase: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-InflateColumn-Object-Enum
requires:
  DBIx::Class::Schema: 0
  Object::Enum: 0
version: 0.06
